/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views;

import Utilities.SetSize;
import java.awt.Dimension;
import java.net.URL;

public class FrmQuanLyDocGia extends javax.swing.JPanel {
    final SetSize setsize = new SetSize();
    public FrmQuanLyDocGia() {
        initComponents();
        this.seticon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnDocGia = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btnTimKiem = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        btnThem = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnSuaThongTin = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jpnLstDocGia = new javax.swing.JPanel();

        jpnDocGia.setBackground(new java.awt.Color(255, 255, 255));
        jpnDocGia.setPreferredSize(new java.awt.Dimension(780, 530));
        jpnDocGia.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        jPanel5.setBackground(new java.awt.Color(125, 200, 150));
        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel5.setPreferredSize(new java.awt.Dimension(780, 50));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTimKiem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTimKiem.setPreferredSize(new java.awt.Dimension(24, 24));
        btnTimKiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTimKiemMouseClicked(evt);
            }
        });
        jPanel5.add(btnTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, -1, -1));

        jTextField1.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField1.setPreferredSize(new java.awt.Dimension(64, 24));
        jTextField1.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        jTextField1.setSelectionColor(new java.awt.Color(0, 0, 0));
        jPanel5.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 174, -1));

        btnThem.setBackground(new java.awt.Color(125, 200, 150));
        btnThem.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(125, 200, 125), null, null));
        btnThem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThemMouseClicked(evt);
            }
        });

        jLabel2.setText("Thêm độc giả");
        btnThem.add(jLabel2);

        jPanel5.add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 100, 28));

        jPanel3.setBackground(new java.awt.Color(125, 200, 150));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(125, 200, 125), null, null));
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel3.setText("Xóa độc giả");
        jPanel3.add(jLabel3);

        jPanel5.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 100, 28));

        btnSuaThongTin.setBackground(new java.awt.Color(125, 200, 150));
        btnSuaThongTin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(125, 200, 125), null, null));
        btnSuaThongTin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSuaThongTin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSuaThongTinMouseClicked(evt);
            }
        });

        jLabel5.setText("Sửa thông tin");
        btnSuaThongTin.add(jLabel5);

        jPanel5.add(btnSuaThongTin, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 100, 30));

        jpnDocGia.add(jPanel5);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(780, 30));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setText("Danh sách độc giả");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 30));

        jpnDocGia.add(jPanel1);

        jScrollPane1.setBackground(new java.awt.Color(125, 200, 150));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(780, 450));

        jpnLstDocGia.setBackground(new java.awt.Color(255, 255, 255));
        jpnLstDocGia.setAutoscrolls(true);
        jpnLstDocGia.setMaximumSize(new java.awt.Dimension(880, 380));
        jpnLstDocGia.setPreferredSize(new java.awt.Dimension(780, 450));
        jpnLstDocGia.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(jpnLstDocGia);

        jpnDocGia.add(jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jpnDocGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jpnDocGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimKiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTimKiemMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTimKiemMouseClicked

    private void btnThemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemMouseClicked
        // TODO add your handling code here:
        FrmDocGia docGia = new FrmDocGia();
        docGia.setVisible(true);
        int i = jpnLstDocGia.getComponentCount();
        if(i>4 && i%2==0){
            jpnLstDocGia.setPreferredSize(new Dimension(WIDTH, jpnLstDocGia.getHeight()+125));
        }
        FrmDocGiaKhung docGiafrm = new FrmDocGiaKhung();
        docGiafrm.setPreferredSize(new Dimension(350, 120));
        jpnLstDocGia.add(docGiafrm);
        jpnLstDocGia.revalidate();
        jpnLstDocGia.repaint();
    }//GEN-LAST:event_btnThemMouseClicked

    private void btnSuaThongTinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuaThongTinMouseClicked
        // TODO add your handling code here:
        FrmDocGia docGia = new FrmDocGia();
        docGia.setVisible(true);
    }//GEN-LAST:event_btnSuaThongTinMouseClicked
    
    private void seticon(){
        URL urlSearch = getClass().getResource("/Images/search.png");
        btnTimKiem.setIcon(setsize.setSizeAnh(urlSearch, 24, 24));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnSuaThongTin;
    private javax.swing.JPanel btnThem;
    private javax.swing.JLabel btnTimKiem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel jpnDocGia;
    private javax.swing.JPanel jpnLstDocGia;
    // End of variables declaration//GEN-END:variables
}
